#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_GOOGLE_include_directive : require

layout(set = 0, binding = 0) uniform sampler2D vkofTextures[];

#include "util-energy-compensation.glsl"

layout(buffer_reference, scalar) buffer F32Buffer { f32 data[]; };
layout(buffer_reference, scalar) buffer F32v3Buffer { f32v3 data[]; };

// per sample: f32v3(mu, roughness, f0)
layout(push_constant, scalar) uniform PC {
	layout(offset = 128) uint64_t inVa;
	uint64_t compensateOutVa;
	uint64_t albedoOutVa;
	uint count;
} pc;

layout(local_size_x = 64) in;

void main() {
	u32 i = gl_GlobalInvocationID.x;
	if (i >= pc.count) { return; }
	const f32v3 s = F32v3Buffer(pc.inVa).data[i];
	F32Buffer(pc.compensateOutVa).data[i] = (
		utilMicrofacetDielectricEnergyCompensate(s.x, s.y, s.z)
	);
	F32Buffer(pc.albedoOutVa).data[i] = (
		utilMicrofacetDielectricAlbedo(s.x, s.y, s.z)
	);
}
