#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_GOOGLE_include_directive : require

#include "util-microfacet.glsl"

layout(buffer_reference, scalar) buffer F32Buffer { f32 data[]; };

// per sample, 5 floats: localH.xyz, alpha.xy
layout(push_constant, scalar) uniform PC {
	layout(offset = 128) uint64_t inVa;
	uint64_t outVa;
	uint count;
} pc;

layout(local_size_x = 64) in;

void main() {
	u32 i = gl_GlobalInvocationID.x;
	if (i >= pc.count) { return; }
	F32Buffer inBuf = F32Buffer(pc.inVa);
	u32 base = i * 5u;
	const f32v3 localH = (
		f32v3(inBuf.data[base+0u], inBuf.data[base+1u], inBuf.data[base+2u])
	);
	const f32v2 alpha = f32v2(inBuf.data[base+3u], inBuf.data[base+4u]);
	F32Buffer(pc.outVa).data[i] = utilMicrofacetGgxDistributionAniso(localH, alpha);
}
