#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_image_load_formatted : require

layout(set = 0, binding = 2) uniform image2D vkofImages[];

layout(buffer_reference, scalar) buffer FloatBuffer {
	float data[];
};

layout(push_constant, scalar) uniform PC {
	layout(offset = 128) uint64_t dstVa;
	uint imgHandle;
	uint width;
	uint height;
} pc;

layout(local_size_x = 64) in;

void main() {
	uint total = pc.width * pc.height;
	uint idx = gl_GlobalInvocationID.x;
	if (idx >= total) { return; }
	ivec2 coord = ivec2(idx % pc.width, idx / pc.width);
	float val = imageLoad(vkofImages[nonuniformEXT(pc.imgHandle)], coord).r;
	FloatBuffer(pc.dstVa).data[idx] = val;
}
