#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_GOOGLE_include_directive : require

layout(set = 0, binding = 0) uniform sampler2D vkofTextures[];

#include "util-random.glsl"

layout(buffer_reference, scalar) buffer F32Buffer {
	float data[];
};

layout(push_constant, scalar) uniform PC {
	layout(offset = 128) uint64_t seedOutVa;
	uint64_t seed2OutVa;
	uint bluenoiseHandle;
	uint frameIndex;
	uint salt;
	uint width;
} pc;

layout(local_size_x = 16, local_size_y = 16) in;

void main() {
	uint x = gl_GlobalInvocationID.x;
	uint y = gl_GlobalInvocationID.y;
	uint idx = y * pc.width + x;

	u64 state, state2;
	f32 seed;
	f32v2 seed2;
	utilGenerateSeeds(
		state, state2, seed, seed2, pc.frameIndex, pc.salt, pc.bluenoiseHandle
	);

	F32Buffer(pc.seedOutVa).data[idx] = seed;
	F32Buffer(pc.seed2OutVa).data[idx * 2u + 0u] = seed2.x;
	F32Buffer(pc.seed2OutVa).data[idx * 2u + 1u] = seed2.y;
}
